### ISSUE TITLE
Withdraw Error

### ISSUE THREAD

**Issue by ProfNeurus** [NeuraiProject/electrum-neurai#4]
Hello, I send XNA to my coinex account but the transaction fail and now I don´t have my XNA neither in Electrum Wallet or Coinex.
The Transaction ID is b349824634ff7c8c72ef07988939371b6fc1513fa1b041218b9f3d9ea6aa66cc
How can I Recover my XNA?

Thanks

**Comment by NeuraiProject** [comment]
The sending is correct, it appears in the blockchain and CoinEx only counts deposits from 1000 XNA. You should check the exchange conditions before sending amounts.

![image](https://github.com/NeuraiProject/electrum-neurai/assets/122438095/0b6e3c39-8a70-4c9f-87b0-44cc99c107b8)

[https://neuraiexplorer.com/tx/b349824634ff7c8c72ef07988939371b6fc1513fa1b041218b9f3d9ea6aa66cc](https://neuraiexplorer.com/tx/b349824634ff7c8c72ef07988939371b6fc1513fa1b041218b9f3d9ea6aa66cc)

I close because there is no problem with Electrum.
